### ISSUE TITLE
Brute Top2000 Password Broken

### ISSUE THREAD

**Issue by kur3us** [carlospolop/PEASS-ng#185]
I believe this commit broke at least the Brute PW functionality if not more...

https://github.com/carlospolop/PEASS-ng/commit/a32932828a2d73b1fb99c266358f3d35590e4845#diff-39122aa0fe2c86237414bba8f426d228c5171d6031ecee9e921f6012f7049d99

Now, it does not print a password found in the top2000 list even though the password is valid. If you revert line 647, it works and prints the password.

```
    #su_try_pwd "$BFUSER" "$(echo "$top2000pwds" | cut -d " " -f "$i")" & #Try TOP TRIES of passwords (by default 2000)
    su_try_pwd $BFUSER `echo $top2000pwds | cut -d " " -f $i` &
```

**Comment by carlospolop** [comment]
Hi @kur3us,

Thank you very much for reporting this bug!
This and other similar bugs should be fixed in the new version. Could you confirm it?

**Comment by kur3us** [comment]
Hi @carlospolop 

I'm seeing a new error during the Brute PW functionality now.

```
╔══════════╣ Testing 'su' as other users with shell using as passwords: null pwd, the username and top2000pwds
                                                                                                                                                                                    
  Bruteforcing user root...
cut: invalid field value ‘"1"’
Try 'cut --help' for more information.
cut: invalid field value ‘"2"’
Try 'cut --help' for more information.
cut: invalid field value ‘"3"’
Try 'cut --help' for more information.
cut: invalid field value ‘"4"’
Try 'cut --help' for more information.
cut: invalid field value ‘"5"’
Try 'cut --help' for more information.
cut: invalid field value ‘"6"’
```

And it keeps going like that.

**Comment by carlospolop** [comment]
Hey @kur3us,

I'm sorry, but I'm on holidays and I can't test the changes. Could you check the last new version and see if that finally works?

**Comment by kur3us** [comment]
Hi @carlospolop, that error is fixed and that functionality now works. Thanks!
