### ISSUE TITLE
why screen software recognized as PE vector ?

### ISSUE THREAD

**Issue by s4miii** [carlospolop/PEASS-ng#188]
Thnx for your great tool
I've installed an old Ubuntu 14.04 on my VM for testing
in this case I set `SGID` for `screen` app on my VM and scanned it via `linpeas` script.
My test user is not root and it's not member of any group.
I noticed that the screen software with `SGID`, is displayed as a `PE vector`.

Is it really dangerous? if yes how to privesc in my scenario ? 
thnx in advance

**Comment by carlospolop** [comment]
Hi @s4miii,

Could you share a screenshot of the specific check you are asking about please?

**Comment by s4miii** [comment]
> Hi @s4miii,
> 
> Could you share a screenshot of the specific check you are asking about please?

Hi thnx for your reply
Sure, for example check these 3 VMs with various versions of Screen (all of them have SGID set).

1)Ubuntu 14.04 3.2.0-126-generic 2017 x86_64
+Screen version 4.01.00devel (GNU) 2-May-06
![Screen Shot 2021-08-04 at 11 16 21](https://user-images.githubusercontent.com/29096708/128136444-b89d2fca-3c19-480b-8d93-a9ec2c48ce54.png)

2)CentOs 6.10 2.6.32-754.9.1.el6.x86_64 2018
+Screen version 4.00.03 (FAU) 23-Oct-06
![Screen Shot 2021-08-04 at 11 22 44](https://user-images.githubusercontent.com/29096708/128136496-76ae7c35-6420-40e3-baac-a0f4a229d969.png)

3)CentOS 5.11 2.6.18-419.el5 2017
+Screen version 4.00.03 (FAU) 23-Oct-06
![Screen Shot 2021-08-04 at 11 25 47](https://user-images.githubusercontent.com/29096708/128136511-482dcbe7-3fa0-414d-90c9-713a5ec9cc85.png)

My question is, if it is really vulnerable, how we can use that for privesc ? 

Thank you again

**Comment by carlospolop** [comment]
Hey mate!
Great question, those aren't actually vectors to escalate privs.
The thing is that linpeas is actually using the same list of GTFOBins to identify binaries that can be abused with suid/sgid. Unfortunately, some of those binaries cannot be abused with suid (like `screen`).
I will improve this list for the next releases of linpeas.
Thanks for reporting this :)

**Comment by carlospolop** [comment]
Hey @s4miii ,

From now on linpeas is generated downloading the binary named from GTFOBins and generating 3 different lists: one for suid bins, another one for sudo bins and another one for cap bins.
This false positive should have disappear as the `screen` name isn't anymore in the sidVB list:
https://github.com/carlospolop/PEASS-ng/blob/9ae642c205de7a4c5abbc166877f3bfb24c49520/linPEAS/linpeas.sh#L362-L363

Also these lists will be auto updated on each new release :)

**Comment by s4miii** [comment]
Tnx a lot bro !
