### ISSUE TITLE
linpeas: Broken scan for problems in SUID programs

### ISSUE THREAD

**Issue by kgraefe** [carlospolop/PEASS-ng#205]
If you are going to suggest something, please remove the following template. 

#### Issue description

When scanning SUID programs on my system none of the "It looks like" suggestions were printed although I know there are at least some.

#### Steps to reproduce the issue

Run `./linpeas.sh -o IntFiles`

#### Which parameters did you use for executing the script and how did you execute it?

`-o IntFiles`

#### Is there any AV / Threat protection in the system?

no

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)

Custom Linux distribution based on Yocto/busybox with customized Linux kernel 5.10.47-rt46.

#### Additional details / screenshot
- The quotes in [linpeas_base.sh#L2560](https://github.com/carlospolop/PEASS-ng/blob/14ebbdb3e2e5edb6d6a2d6fa6a501992563c4dde/linPEAS/builder/linpeas_base.sh#L2560) should not be escaped. `$sline_first` becomes e.g. `"cat"` where it should be `cat`. This is broken since https://github.com/carlospolop/PEASS-ng/commit/fbe0004755b9cf1df19778bc6986cd361889a331
- On my machine `grep -qv ".."` in [linpeas_base.sh#L2567](https://github.com/carlospolop/PEASS-ng/blame/14ebbdb3e2e5edb6d6a2d6fa6a501992563c4dde/linPEAS/builder/linpeas_base.sh#L2567) matches any characters, basically disabling `printf` completely. The dots should be escaped. This is broken since https://github.com/carlospolop/PEASS-ng/commit/883e5b56e6c9fe4708039d963649fb554c5bf63e .

**Comment by carlospolop** [comment]
Thanks @kgraefe for your suggestions.
This should be fixed now as I followed the indicated fixes, could you check?

**Comment by kgraefe** [comment]
I does NOT work for me. I will investigate and create a PR this time. ;-)

**Comment by carlospolop** [comment]
The PR was accepted and a new linpeas was generated.
Thanks for reporting this issue!
