### ISSUE TITLE
specify output file path

### ISSUE THREAD

**Issue by Doctor-Venom** [carlospolop/PEASS-ng#207]
At this moment we can only use the "log" flag to redirect all output to "out.txt".
It would be great if we are be able to specify the path of the output file.

**Comment by carlospolop** [comment]
I'm assuming you are asking about winpeas, as in linpeas there isn't such option.

**Comment by Doctor-Venom** [comment]
Yeah, I had a scenario where I needed this option in winpeas.

**Comment by makikvues** [comment]
hello @Doctor-Venom thanks for the comment - this should be fixed in next PR, please check it once the PR is merged so we can close the issue. thx
