### ISSUE TITLE
stuck at ssl/ssh files scan

### ISSUE THREAD

**Issue by jafar-pathan** [carlospolop/PEASS-ng#241]
#### Issue description
linPEASS stopped working and stucked at ssl/ssh files searching. It is not doing anything as its load on cpu is 0.0%. 

#### Which parameters did you use for executing the script and how did you execute it?
./linpeas.sh
./linpeas.sh -s 

#### Is there any AV / Threat protection in the system?
No.

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
OS - Kali GNU/Linux Rolling x86_64
OS Version - 2021.4
Kernel: 5.14.0-kali4-amd64

#### Please, indicate the check that is failing and add a screenshot showing the problem
Two screenshots are attached. one is of the linpeas.sh stuck and other is of htop showing linpeas.sh process stuck.

#### How did you expect it to work?
If it takes some time or it is usual to stuck at ssl/ssh scan any information should be provided.

#### Additional details / screenshot
My system is has internet connection while running script and i have dual booted kali linux.

![stuck](https://user-images.githubusercontent.com/65374935/144198937-96c1dcd5-ae4f-4187-8946-5bb08ff448d9.png)
![htopLinPEASSprocessStuck](https://user-images.githubusercontent.com/65374935/144198949-5d9d6d30-6918-4c28-8e96-7a3ee69a3741.png)

**Comment by carlospolop** [comment]
Hi @jafar-pathan,

I tried linpeas in a Kali 2021.4 and it didn't stop, so probably is something specific in your machine.
It would be awesome if you could try to figure out in which line of the script the execution is stopped exactly, could you do this?

**Comment by carlospolop** [comment]
Hi @jafar-pathan,

I closed this issue because you weren't responding.
If you can send more info to fix this issue feel free to reopen the issue :)
