### ISSUE TITLE
Update documentation: winPEAS.exe requires for obfuscation also an exception in Defender / AV

### ISSUE THREAD

**Issue by new-gen23** [carlospolop/PEASS-ng#258]
#### Suggestion: Update Documentation to include exception folders in Defender. 

If the obfuscation with Dotfuscator is necessary (often the case in legal security assessments), it is recommended to create a folder in Windows Defender that is excluded from scanning. This is required for the compilation in Visual Studio. However, it is also necessary for the obfuscation. One has to keep in mind that both, Visual Studio and Dotfuscator, require the input + temporary files + output within this exception folder. Otherwise, obfuscation will fail during compilation, as Defender will flag the temporary files in stub-pdb.

#### Is there any AV / Threat protection in the system?
Windows Defender

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
Windows 10

#### Please, indicate the check that is failing and add a screenshot showing the problem
![image](https://user-images.githubusercontent.com/1741662/148418852-e7ffee6a-c270-4e26-bf38-bb8977b3ad9c.png)

**Comment by carlospolop** [comment]
Hi @new-gen23!
Please, could you share also the instructions to create the exception for defender so I can update the documentation?

**Comment by carlospolop** [comment]
I just added your image to the readme to indicate that. Thanks!
