### ISSUE TITLE
Linpeas [Feature]: Add check for rocketchat creds

### ISSUE THREAD

**Issue by unkn0wnsyst3m** [carlospolop/PEASS-ng#271]
Please include a check for rocketchat authentication password with the mongodb service

```
cat /lib/systemd/system/rocketchat.service 
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://rocket:my$ecretPass@localhost:27017/rocketchat?replicaSet=rs01&authSource=rocketchat
Environment=MONGO_OPLOG_URL=mongodb://rocket:my$ecretPass@localhost:27017/local?replicaSet=rs01&authSource=admin
Environment=ROOT_URL=http://<removed>/
Environment=PORT=48320
Environment=BIND_IP=127.0.0.1
Environment=DEPLOY_PLATFORM=rocketchatctl
[Install]
WantedBy=multi-user.target
```
grep script:

```
cat /lib/systemd/system/rocketchat.service  | grep -oP '(?=mongodb).*(?=/)'
mongodb://rocket:my$ecretPass@localhost:27017
```

mongodb standard URI:
https://docs.mongodb.com/manual/reference/connection-string/
rocket chat service config:
https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/debian-based-distros/debian

**Comment by carlospolop** [comment]
Hi @unkn0wnsyst3m,

Thanks for letting me know!
I have added it in https://github.com/carlospolop/PEASS-ng/commit/7f0bbdbaaee7685db6d14b3b0852a10130f7f296
I would be awesome if you could test the latest version once it's builrt in a couple of hours

**Comment by unkn0wnsyst3m** [comment]
@carlospolop it works perfectly!  thanks and well done!

**Comment by carlospolop** [comment]
Thanks for checking!
