### ISSUE TITLE
Why the binaries are missing from this 

### ISSUE THREAD

**Issue by sanjay-panchal** [carlospolop/PEASS-ng#276]
![Screenshot 2022-03-06 at 5 43 25 PM](https://user-images.githubusercontent.com/99550332/156922599-f9d1c363-64f5-417a-b9f8-c38d96557ecb.png)

There should be exe binaries in the folder, but it's empty. Same for x86, obfuscated also.

**Comment by rautamiekka** [comment]
No, that would be abuse of Git cuz
1) Git ain't meant for binary data versioning.
1) GitHub has a release section for that purpose.

**Comment by carlospolop** [comment]
Hi @sanjay-panchal,
As mentioned in the README (https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS/winPEASexe) the new releases are in the releases section: https://github.com/carlospolop/PEASS-ng/releases
