### ISSUE TITLE
Feature request: List all files and folders under /opt

### ISSUE THREAD

**Issue by securitytime** [carlospolop/PEASS-ng#281]
I just had an HTB machine which had an important file under /opt which was needed for privilege escalation. LinPEAS missed this one. It's not the first time I had important files under /opt.

Usually, the /opt folder is empty. So any files or folders under /opt are noteworthy.

For the "interesting files" section, there should be a new test which simply lists all files and folders under /opt.

**Comment by carlospolop** [comment]
Hi @securitytime,
Thanks for the suggestion, you should find this functionality in the next release!
