### ISSUE TITLE
Add offline filesystem scan option

### ISSUE THREAD

**Issue by Novitoll** [carlospolop/PEASS-ng#284]
Would like to use LinPeas.sh for Linux filesystem scan where you have dumped the filesystem and scanning for passwords, sensitive information only, without checking network, running processes etc.

**Comment by clem9669** [comment]
Do you mean like grep and find commands ?

**Comment by Novitoll** [comment]
Commands, passwords, interesting SUID binaries, cronjobs etc. E.g. only filesystem with available DAC file permissions (assuming that permissions have not changed).

You have dumped an image of rootfs and you want to run LinPEAS against it, without enumerating processes, network as it will show your local system info, I want to enum only dumped rootfs

**Comment by carlospolop** [comment]
Hi @Novitoll,
Actually you can find that option in the paid version of linpeas (https://github.com/sponsors/carlospolop), which allows you to specify a folder with the `-f` param. Moreover, that paid version contains more interesting files to search and more regexes to run over files to find more sensitive information.
Regarding the community version, the best way is to chroot in the filesystem you want to analyze and run linpeas.
