### ISSUE TITLE
Can you produce a Chinese version？

### ISSUE THREAD

**Issue by TryA9ain** [carlospolop/PEASS-ng#286]

**Comment by clem9669** [comment]
Hello 👋 

Do you mean to translate the README.md in various languages ?

**Comment by carlospolop** [comment]
Hi @TryA9ain,

If you mean about the readme I don'thave that in my plans.
If you mean about hacktricks, feel free to open an issue in hacktricks github, I hope I will be able to offer hacktricks in different languages in the future
