### ISSUE TITLE
hacktricks results links are obsolete

### ISSUE THREAD

**Issue by hazeyez** [carlospolop/PEASS-ng#287]
Hey, first of all - what an absolute amazing tool you have built. Many props to you!!!

Wondering if you're going to update the hacktricks links that linpeas spits out in the results? a lot of them are obsolete or broken.

Example:
https://book.hacktricks.xyz/linux-unix/privilege-escalation#open-shell-sessions **---> from linpeas results**
https://book.hacktricks.xyz/linux-hardening/privilege-escalation#open-shell-sessions **---> actual link on hacktricks**

Using the linpeas.sh file, by the way and I'm pretty sure it's most current.  Of course I can just search the hacktricks site, but it's more convenient to click the link to the section you're referencing - especially when you are new to this & to be sure I'm viewing exactly what you are referencing. Also, their search feature is not great. This happens with more than just the link above, only using it for reference.

Keep up the good work!

**Comment by carlospolop** [comment]
Hi @hazeyez,
It looks like you probably aren't using the latest version.
The new versions of PEASS are in the github releases page (https://github.com/carlospolop/PEASS-ng/releases/latest) and I cannot find any "/linux-unix/" link in the latest linpeas.sh...
Please, check that releases and feel free to reopen the issue if I'm missing something
