### ISSUE TITLE
Kerberos Keytab Files

### ISSUE THREAD

**Issue by godylockz** [carlospolop/PEASS-ng#303]
In linpeas.sh, under Kerberos. I think there should be a task to find `*.keytab` files if a `/etc/krb5.conf` exists.

There was a file /etc/krb5.keytab and it can be used to extract credentials via https://github.com/sosdave/KeyTabExtract

**Comment by carlospolop** [comment]
Hi @godylockz,
With the commit 56d71ae84745e457d3c1c08d997a4bc2f3ea7c5b linpeas should find all the keytab files
Let me know if it doesn't

**Comment by godylockz** [comment]
@carlospolop I was trying to find instructions on how to build a new release of linpeas to try out these changes, could find it. Sorry!

**Comment by carlospolop** [comment]
My fault, I need to write that doc.
Anyway, in a couple of hours a new release should be published with those changes

**Comment by godylockz** [comment]
Thanks carlos!
