### ISSUE TITLE
LinPeas Error: peass{VARIABLES}: not found

### ISSUE THREAD

**Issue by Billhazoide** [carlospolop/PEASS-ng#310]
If you are going to suggest something, please remove the following template. 

#### Issue description
LinPeas is giving the error appears "./linpeas.sh: 465: ./linpeas.sh: peass{VARIABLES}: not found", and stop the process.

#### Steps to reproduce the issue

1.  Tryhackme Basic Pentest Room (https://tryhackme.com/room/basicpentestingjt)
2. Upload linpeas.sh to the remote machine via SSH in the folder /dev/shm/
3. Make executable with command "chmod +x linpeas.sh" and execute

 OBS: I tried using Kali LTS version and Depin 20.6 (My host), target machine Ubuntu 5.4.0-6 (16.04.9)

![Capturar_select-area_20220903182702](https://user-images.githubusercontent.com/53276690/188288167-a76f1cd7-eff3-48b7-8aa5-7bba1e871ab8.png)

**Comment by carlospolop** [comment]
Hi @Billhazoide,
Which linpeas.sh are you using?

**Comment by Billhazoide** [comment]
Hi!

**Comment by Billhazoide** [comment]
Hi!,
I'm using the latest version, i believe, 2.6.8.

**Comment by carlospolop** [comment]
Hi @Billhazoide,
I don't know where you got a linpeas.sh that triggers that error or where did you see that version (that kind of versions aren't used in this projects for years), but the releases of linpeas and winpeas are in https://github.com/carlospolop/PEASS-ng/releases/latest
Downloading it from there should fix that error
