### ISSUE TITLE
Incorrect syntax in find command

### ISSUE THREAD

**Issue by pathinthefog** [carlospolop/PEASS-ng#315]
#### Issue description

The `find` command (line 1654 of linpeas.sh) inside the `enumerateDockerSockets` function has incorrect syntax. The error message goes unnoticed because of `2>/dev/null`.

The `-n` flag present before `-name 'containerd.sock'` results in the following errors:

`find: unknown predicate '-n'` or `find: unrecognized: -n`

#### Which parameters did you use for executing the script and how did you execute it?

`-o container` to run the script with just the output of the "Container" section, and removed `2>/dev/null` from the aforementioned find command to see if it was throwing an error.

#### Is there any AV / Threat protection in the system?

No

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)

Linux DESKTOP 5.15.0-47-generic #51-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

#### Please, indicate the check that is failing and add a screenshot showing the problem

![image](https://user-images.githubusercontent.com/69284045/191518747-926e18bf-dc3d-4977-9ae6-e9e90381a6e9.png)

#### How did you expect it to work?

I believe the script should also look for a file called "containerd.sock" so the correct flag might be `-o`. Or maybe it was intended for the script to NOT look for the "containerd.sock" file, in which case, the flag should be `-not` or `!`.

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/69284045/191519527-d5203822-0aaa-40ee-9188-87dbce12db4d.png)

**Comment by carlospolop** [comment]
Thanks!
The next release will have this bug fixed
