### ISSUE TITLE
Link for Docker container escape points to a non-existing page

### ISSUE THREAD

**Issue by 0xsyr0** [carlospolop/PEASS-ng#316]
This link needs to be updated i think:

`Docker socket /var/run/docker.sock is writable (https://book.hacktricks.xyz/linux-unix/privilege-escalation#writable-docker-socket)`

With this one `https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-breakout/abusing-docker-socket-for-privilege-escalation` i guess.

Maybe it was moved.

**Comment by carlospolop** [comment]
Hi @0xsyr0,
You might be using an outdated version because in the current version there is no link to the folder "/linux-unix".

If I'm wrong feel free to reopen the issue indicating the file that contains the bad link please
