### ISSUE TITLE
Hangs during testing

### ISSUE THREAD

**Issue by primetimenumberline** [carlospolop/PEASS-ng#317]
If you are going to suggest something, please remove the following template. 

#### Issue description
I'm admittedly new to the pentesting space, and I was looking to harden my system and I found winpeas and decided to try to run a copy of the x64 exe and its been stuck at 53% during a check that I think is called "SSH Agent Files". Not sure if this is me just being a newbie or not, but I figured I'd at least post, and also thank you for compiling such a cool list of tests. I'm excited to get this running on my machine! Cheers and thank you!

#### Steps to reproduce the issue

1.  
2. 
3.

#### Which parameters did you use for executing the script and how did you execute it?
I turned of windows' antivirus software through control panel (windows defender) and then I ran the .exe for x64obf

#### Is there any AV / Threat protection in the system?
I turned off windows defender

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
Windows 10 Home 21H2 19044.2006

#### Please, indicate the check that is failing and add a screenshot showing the problem
![image](https://user-images.githubusercontent.com/96997557/192836007-ed7a3d19-81fe-4293-9680-b90328f862f3.png)

#### How did you expect it to work?
I expected it to go from 53% to 54% ... eventually ... lol jk jk, but yeah, I think it might have hung on me. It's been not quite an hour, but a really long time.

#### Additional details / screenshot
I tried to attach a screenshot, I hope it works.

**Comment by carlospolop** [comment]
your issue is the same one as the one in https://github.com/carlospolop/PEASS-ng/issues/312
lets discuss it in there
