### ISSUE TITLE
Color scheme for the kerberos ticket module

### ISSUE THREAD

**Issue by TheThingGoesSkra** [carlospolop/PEASS-ng#334]
Hello ! First of all, thanks you for the amazing job you've done.

What do you think about adding a color scheme to the kerberos ticket module ? 

For example, you could print in red the tickets giving access to a service on a different AD machine ?

Cordially

**Comment by carlospolop** [comment]
Hi @TheThingGoesSkra,

That sounds pretty good! Feel free to send a PR for that please
