### ISSUE TITLE
Curl to Bash returns "Unexpected EOF"

### ISSUE THREAD

**Issue by Sp0kane** [carlospolop/PEASS-ng#342]
If you are going to suggest something, please remove the following template. 

#### Issue description
Executing `curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | bash`  on Ubuntu 22.04.2 LTS installation returns an error immediately after finishing Directory caching.
Like so:
"""
Caching directories . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . DONE

bash: line 1466: unexpected EOF while looking for matching `"'
bash: line 1467: syntax error: unexpected end of file
"""
#### Steps to reproduce the issue

1. Open a terminal in Ubuntu 22.04.2 LTS
2. Run `curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | bash`
3. Profit.

#### Which parameters did you use for executing the script and how did you execute it?
See step two.

#### Is there any AV / Threat protection in the system?
No.

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)  
Linux REDACTED 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

#### Additional details / screenshot
"""
Caching directories . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . DONE

bash: line 1466: unexpected EOF while looking for matching `"'
bash: line 1467: syntax error: unexpected end of file
"""

**Comment by Sp0kane** [comment]
Aaand `curl -s -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh|sh` runs without errors.

**Comment by carlospolop** [comment]
is this still hapening with the latest versions @Sp0kane ?
