### ISSUE TITLE
Include pwsh in Useful Software

### ISSUE THREAD

**Issue by ClutchReboot** [carlospolop/PEASS-ng#343]
#### Issue description
Useful Software section does not appear to include `pwsh`.

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
Ubuntu 22.04.1 LTS
Linux version 5.15.0-43-generic

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/39310845/226390830-f21a87ca-9681-4788-8ea9-1765d35b9b4a.png)

```bash
$ which pwsh
/usr/bin/pwsh
```

**Comment by carlospolop** [comment]
Hi @ClutchReboot,
Good idea, done in https://github.com/carlospolop/PEASS-ng/commit/0682cafe0855bb55899aeca24530663da1d7cb86, next time consider sending a PR!
