### ISSUE TITLE
Typos in linpeas.sh

### ISSUE THREAD

**Issue by jahatfi** [carlospolop/PEASS-ng#372]
If you are going to suggest something, please remove the following template. 
If your issue is related with WinPEAS.ps1 please mention https://github.com/RandolphConley

#### Issue description
1. Line 456 of linpeas_bash.sh contains "noboby", I think this should be "nobody"
2. Line 1142 is "  ##### POST SERACH VARIABLES #####", it should be "  ##### POST SEARCH VARIABLES #####
"
#### Steps to reproduce the issue

N/A

#### Which parameters did you use for executing the script and how did you execute it?
N/A

#### If winpeas, did you use a clean or obfuscated winpeas, and for which architecture?
N/A

#### Is there any AV / Threat protection in the system?
N/A

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
N/A

#### Please, indicate the check that is failing and add a screenshot showing the problem
N/A

#### How did you expect it to work?
N/A

#### Additional details / screenshot
N/A

**Comment by carlospolop** [comment]
thanks
