### ISSUE TITLE
Why is the new version of linpeas.sh missing the Executing Linux Explore Suggester module

### ISSUE THREAD

**Issue by gaishidabaojian** [carlospolop/PEASS-ng#381]
Why is the new version of linpeas.sh missing the Executing Linux Explore Suggester module
![image](https://github.com/carlospolop/PEASS-ng/assets/75197329/f106a030-3fc2-4da0-ba64-d7bba9d38f7f)

**Comment by carlospolop** [comment]
good call, it looks like in the previous month half of the code of the first module disappeared. I have added it again, it should be working in the new version.
